[colors.bright]
black = "#32302f"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"

[colors.normal]
black = "#32302f"
blue = "#83a598"
cyan = "#83a598"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fe8019"

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[font]
size = 12

[font.normal]
family = "JetBrainsMono NF"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
opacity = 0.9

[selection]
save_to_clipboard = true
